PGROUTING: /home/nazii/PGR/src/common/arrays_input.c File Reference
arrays_input.c File Reference
#include "c_common/arrays_input.h"
#include <assert.h>
#include "utils/lsyscache.h"
#include "catalog/pg_type.h"
#include "c_common/time_msg.h"
#include "c_common/debug_macro.h"
Functions
static int64_t * pgr_get_bigIntArr (ArrayType *v, size_t *arrlen, bool allow_empty)
Function returns the values of input array by checking its overflow conditions.
int64_t * pgr_get_bigIntArray (size_t *arrlen, ArrayType *input)
Function returns the values of input array by checking its overflow conditions but array can't empty.
int64_t * pgr_get_bigIntArray_allowEmpty (size_t *arrlen, ArrayType *input)
Function returns the values of input array by checking its overflow conditions but array can empty.
Function Documentation
pgr_get_bigIntArr()
static int64_t* pgr_get_bigIntArr (ArrayType * v, size_t * arrlen, bool allow_empty) static
Function returns the values of input array by checking its overflow conditions.
Parameters
v array object to examine.
arrlen Number of elements in an array.
allow_empty Tell whether array can empty or not.
Functions Used
get_typlenbyvalalign() : Given the type of OID return the value of typlen, typbyval, typalign.
deconstruct_array() : Simple method for extracting data from an array.
Description
Function will check following conditions:
Return NULL if array is empty.
if (allow_empty && (ndim == 0 || nitems <= 0)) {
      PGR_DBG("ndim %i nitems % i", ndim, nitems);
      return (int64_t*) NULL;
Return NULL if array is multi-dimension or no dimension.
if (ndim != 1) {
      elog(ERROR, "One dimension expected");
      return (int64_t*)NULL;
Return NULL if no element found in an array.
if (nitems <= 0) {
      elog(ERROR, "No elements found");
      return (int64_t*)NULL;
Validate input data type is ANY-INTEGER or not .
Store the value of an array in c_array and return.
Returns
Return the pointer of an array.
References
Postgres arrays ArrayGetNItems deconstruct_array() get_typlenbyvalalign() typlen typbyval typalign fetch_att INT2OID INT4OID INT8OID DatumGetInt16 DatumGetInt32 DatumGetInt62
Definition at line 100 of file arrays_input.c.
References PGR_DBG, and time_msg().
Referenced by pgr_get_bigIntArray(), and pgr_get_bigIntArray_allowEmpty().
{
     clock_t start_t = clock();
     int64_t *c_array = NULL;;
     Oid     element_type = ARR_ELEMTYPE(v);
     int    *dim = ARR_DIMS(v);
     int     ndim = ARR_NDIM(v);
     int     nitems = ArrayGetNItems(ndim, dim);
     Datum  *elements;
     bool   *nulls;
     int16   typlen;
     bool    typbyval;
     char    typalign;
     assert((*arrlen) == 0);
     if (allow_empty && (ndim == 0 || nitems <= 0)) {
         PGR_DBG("ndim %i nitems % i", ndim, nitems);
         return (int64_t*) NULL;
     }
     /* the array is not empty*/
     if (ndim != 1) {
         elog(ERROR, "One dimension expected");
         return (int64_t*)NULL;
     }
     if (nitems <= 0) {
         elog(ERROR, "No elements found");
         return (int64_t*)NULL;
     }
     get_typlenbyvalalign(element_type,
             &typlen, &typbyval, &typalign);
     /* validate input data type */
     switch (element_type) {
         case INT2OID:
         case INT4OID:
         case INT8OID:
             break;
         default:
             elog(ERROR, "Expected array of ANY-INTEGER");
             return (int64_t*)NULL;
             break;
     }
     deconstruct_array(v, element_type, typlen, typbyval,
             typalign, &elements, &nulls,
             &nitems);
     c_array = (int64_t *) palloc(sizeof(int64_t) * (size_t)nitems);
     if (!c_array) {
         elog(ERROR, "Out of memory!");
     }
     int i;
     for (i = 0; i < nitems; i++) {
         if (nulls[i]) {
             pfree(c_array);
             elog(ERROR, "NULL value found in Array!");
         } else {
             switch (element_type) {
                 case INT2OID:
                     c_array[i] = (int64_t) DatumGetInt16(elements[i]);
                     break;
                 case INT4OID:
                     c_array[i] = (int64_t) DatumGetInt32(elements[i]);
                     break;
                 case INT8OID:
                     c_array[i] = DatumGetInt64(elements[i]);
                     break;
             }
         }
     }
     (*arrlen) = (size_t)nitems;
     pfree(elements);
     pfree(nulls);
     PGR_DBG("Array size %ld", (*arrlen));
     time_msg("reading Array", start_t, clock());
     return c_array;
 }
pgr_get_bigIntArray()
int64_t* pgr_get_bigIntArray (size_t * arrlen, ArrayType * input)
Function returns the values of input array by checking its overflow conditions but array can't empty.
enforces the input array to be NOT empty
Parameters
input array object to examine.
arrlen Number of elements in an array.
Returns
Return the pointer of an array.
Definition at line 195 of file arrays_input.c.
References pgr_get_bigIntArr().
Referenced by compute_trsp(), pgr_SPI_getBigIntArr(), and process().
{
     return pgr_get_bigIntArr(input, arrlen, false);
 }
pgr_get_bigIntArray_allowEmpty()
int64_t* pgr_get_bigIntArray_allowEmpty (size_t * arrlen, ArrayType * input)
Function returns the values of input array by checking its overflow conditions but array can empty.
Allows the input array to be empty.
Parameters
input array object to examine.
arrlen Number of elements in an array.
Returns
Return the pointer of an array.
Definition at line 209 of file arrays_input.c.
References pgr_get_bigIntArr().
Referenced by process().
{
     return pgr_get_bigIntArr(input, arrlen, true);
 }