PGROUTING: /home/nazii/PGR/include/c_common/get_check_data.h File Reference
get_check_data.h File Reference
#include "c_common/postgres_connection.h"
#include "c_types/column_info_t.h"
Functions
bool column_found (int colNumber)
Function will check whether the colNumber represents any specified column or NULL (SPI_ERROR_NOATTRIBUTE).
void pgr_check_any_integer_type (Column_info_t info)
The function check whether column type is ANY-INTEGER or not.
void pgr_check_any_integerarray_type (Column_info_t info)
The function check whether column type is ANY-INTEGER-ARRAY or not.
void pgr_check_any_numerical_type (Column_info_t info)
The function check whether column type is ANY-NUMERICAL.
void pgr_check_boolean_type (Column_info_t info)
void pgr_check_char_type (Column_info_t info)
The function check whether column type is CHAR or not.
void pgr_check_text_type (Column_info_t info)
The function check whether column type is TEXT or not.
void pgr_fetch_column_info (Column_info_t info[], int info_size)
Function tells expected type of each column and then check the correspondence type of column.
int64_t pgr_SPI_getBigInt (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
Function returns the value of the specified column in integer type.
int64_t * pgr_SPI_getBigIntArr (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, uint64_t *the_size)
Function returns the values of the specified columns in array.
char pgr_SPI_getChar (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info, bool strict, char default_value)
Function returns the value of the specified column in char type.
double pgr_SPI_getFloat8 (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
Function returns the value of the specified column in double type.
char * pgr_SPI_getText (HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info)
under development
Function Documentation
column_found()
bool column_found (int colNumber)
Function will check whether the colNumber represents any specified column or NULL (SPI_ERROR_NOATTRIBUTE).
Parameters
colNumber Column number (count starts at 1).
Returns
true when colNumber exists false when colNumber was not found
References
SPI_fnumber SPI_ERROR_NOATTRIBUTE
Definition at line 47 of file get_check_data.c.
Referenced by fetch_basic_edge(), fetch_column_info(), fetch_edge(), fetch_edge_with_xy(), fetch_pd_orders(), fetch_point(), fetch_vehicles(), and pgr_fetch_row().
{
     return !(colNumber == SPI_ERROR_NOATTRIBUTE);
 }
pgr_check_any_integer_type()
void pgr_check_any_integer_type (Column_info_t info)
The function check whether column type is ANY-INTEGER or not.
For ANY-INTEGER the value of column type must be 21(INT2OID) or 23(INT4OID) or 20(INT8OID).
Returns
NULL is always returned.
References
INT2OID INT4OID INT8OID
Definition at line 209 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == INT2OID
                 || info.type == INT4OID
                 || info.type == INT8OID)) {
         elog(ERROR,
                 "Unexpected Column '%s' type. Expected ANY-INTEGER",
                 info.name);
     }
 }
pgr_check_any_integerarray_type()
void pgr_check_any_integerarray_type (Column_info_t info)
The function check whether column type is ANY-INTEGER-ARRAY or not.
For ANY-INTEGER-ARRAY the value of column type must be 1005(INT2ARRAYOID) or 1007(INT4ARRAYOID) or 1016.
Returns
NULL is always returned.
References
INT2ARRAYOID INT4ARRAYOID
Definition at line 232 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == INT2ARRAYOID
                 || info.type == INT4ARRAYOID
                 || info.type == 1016)) {
         elog(ERROR,
                 "Unexpected Column '%s' type. Expected ANY-INTEGER-ARRAY",
                 info.name);
     }
 }
pgr_check_any_numerical_type()
void pgr_check_any_numerical_type (Column_info_t info)
The function check whether column type is ANY-NUMERICAL.
For ANY-NUMERICAL the value of column type must be 21(INT2OID) or 23(INT4OID) or 20(INT8OID) or 700(FLOAT4OID) or 701(FLOAT8OID).
Returns
NULL is always returned.
References
INT2OID INT4OID INT8OID FLOAT4OID FLOAT8OID
Definition at line 258 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == INT2OID
                 || info.type == INT4OID
                 || info.type == INT8OID
                 || info.type == FLOAT4OID
                 || info.type == FLOAT8OID)) {
         elog(ERROR,
                 "Unexpected Column '%s' type. Expected ANY-NUMERICAL",
                 info.name);
     }
 }
pgr_check_boolean_type()
void pgr_check_boolean_type (Column_info_t info)
pgr_check_char_type()
void pgr_check_char_type (Column_info_t info)
The function check whether column type is CHAR or not.
For CHAR the value of column type must be 1042(BPCHAROID).
Returns
NULL is always returned.
References
BPCHAROID
Definition at line 170 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == BPCHAROID)) {
         elog(ERROR, "Unexpected Column '%s' type. Expected CHAR", info.name);
     }
 }
pgr_check_text_type()
void pgr_check_text_type (Column_info_t info)
The function check whether column type is TEXT or not.
For TEXT column the value of column type must be 25(TEXTOID).
Returns
NULL is always returned.
References
TEXTOID
Definition at line 188 of file get_check_data.c.
References Column_info_t::name, and Column_info_t::type.
Referenced by pgr_fetch_column_info().
{
     if (!(info.type == TEXTOID)) {
         elog(ERROR, "Unexpected Column '%s' type. Expected TEXT", info.name);
     }
 }
pgr_fetch_column_info()
void pgr_fetch_column_info (Column_info_t info[], int info_size)
Function tells expected type of each column and then check the correspondence type of column.
Parameters
info[] contain one or more column information.
info_size number of columns.
Column expected type should be:
ANY_INTEGER
ANY_NUMERICAL
TEXT
CHAR1
ANY_INTEGER_ARRAY
Returns
NULL is always returned.
Definition at line 128 of file get_check_data.c.
References ANY_INTEGER, ANY_INTEGER_ARRAY, ANY_NUMERICAL, CHAR1, fetch_column_info(), pgr_check_any_integer_type(), pgr_check_any_integerarray_type(), pgr_check_any_numerical_type(), pgr_check_char_type(), pgr_check_text_type(), and TEXT.
Referenced by get_edges_5_columns(), get_edges_9_columns(), get_edges_basic(), get_edges_flow(), pgr_get_coordinates(), pgr_get_matrixRows(), pgr_get_pd_orders_general(), pgr_get_points(), pgr_get_restrictions(), and pgr_get_vehicles_general().
{
     int i;
     for (i = 0; i < info_size; ++i) {
         if (fetch_column_info(&info[i])) {
             switch (info[i].eType) {
                 case ANY_INTEGER:
                     pgr_check_any_integer_type(info[i]);
                     break;
                 case ANY_NUMERICAL:
                     pgr_check_any_numerical_type(info[i]);
                     break;
                 case TEXT:
                     pgr_check_text_type(info[i]);
                     break;
                 case CHAR1:
                     pgr_check_char_type(info[i]);
                     break;
                 case ANY_INTEGER_ARRAY:
                     pgr_check_any_integerarray_type(info[i]);
                     break;
                 default:
                     elog(ERROR, "Unknown type of column %s", info[i].name);
             }
         }
     }
 }
pgr_SPI_getBigInt()
int64_t pgr_SPI_getBigInt (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info)
Function returns the value of the specified column in integer type.
Parameters
tuple input row to be examined.
tupdesc input row description.
info contain column information.
Return the binary value of the specified column and stored in binval.
binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
Todo:
Found the specified value of column.
Returns
Integer type in 64 bits of column value is returned.
References
SPI_getbinval INT2OID INT4OID INT8OID DatumGetInt16 DatumGetInt32 DatumGetInt62
Definition at line 390 of file get_check_data.c.
References Column_info_t::colNumber, Column_info_t::name, and Column_info_t::type.
Referenced by fetch_basic_edge(), fetch_edge(), fetch_edge_with_xy(), fetch_pd_orders(), fetch_point(), fetch_restriction(), fetch_vehicles(), and pgr_fetch_row().
{
     Datum binval;
     bool isnull;
     int64_t value = 0;
     binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
     if (isnull)
         elog(ERROR, "Unexpected Null value in column %s", info.name);
     switch (info.type) {
         case INT2OID:
             value = (int64_t) DatumGetInt16(binval);
             break;
         case INT4OID:
             value = (int64_t) DatumGetInt32(binval);
             break;
         case INT8OID:
             value = DatumGetInt64(binval);
             break;
         default:
             elog(ERROR,
                     "Unexpected Column type of %s. Expected ANY-INTEGER",
                     info.name);
     }
 #if 0
     // todo Value of specified column was found.
 #endif
     return value;
 }
pgr_SPI_getBigIntArr()
int64_t* pgr_SPI_getBigIntArr (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, uint64_t * the_size)
Function returns the values of the specified columns in array.
Parameters
tuple input row to be examined.
tupdesc input row description.
info contain column information.
the_size number of element in array.
Return the binary value of the specified column and stored in binval.
binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
Returns
Pointer of columns value is returned.
References
SPI_getbinval DatumGetArrayTypeP pgr_get_bigIntArray
Definition at line 347 of file get_check_data.c.
References Column_info_t::colNumber, and pgr_get_bigIntArray().
Referenced by fetch_restriction().
{
     bool is_null = false;
     Datum raw_array = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &is_null);
     ArrayType *pg_array = DatumGetArrayTypeP(raw_array);
     return (int64_t*) pgr_get_bigIntArray(the_size, pg_array);
 }
pgr_SPI_getChar()
char pgr_SPI_getChar (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info, bool strict, char default_value)
Function returns the value of the specified column in char type.
Parameters
tuple input row to be examined.
tupdesc input row description.
info contain column information.
strict boolean value of strict.
default_value returned when column contain NULL value.
Return the binary value of the specified column and stored in binval.
binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
Returns
Char type of column value is returned.
References
SPI_getbinval BPCHAROID Datum
Definition at line 299 of file get_check_data.c.
References Column_info_t::colNumber, Column_info_t::name, and Column_info_t::type.
Referenced by fetch_point().
{
     Datum binval;
     bool isNull;
     char value = default_value;
     binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isNull);
     if (!(info.type == BPCHAROID)) {
         elog(ERROR, "Unexpected Column type of %s. Expected CHAR", info.name);
     }
     if (!isNull) {
         value =  ((char*)binval)[1];
     } else {
         if (strict) {
             elog(ERROR, "Unexpected Null value in column %s", info.name);
         }
         value = default_value;
     }
     return value;
 }
pgr_SPI_getFloat8()
double pgr_SPI_getFloat8 (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info)
Function returns the value of the specified column in double type.
Parameters
tuple input row to be examined.
tupdesc input row description.
info contain column information.
Return the binary value of the specified column and stored in binval.
binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
Todo:
Found the specified value of column.
Returns
Double type of column value is returned.
References
SPI_getbinval INT2OID INT4OID INT8OID FLOAT4OID FLOAT8OID DatumGetInt16 DatumGetInt32 DatumGetInt62 DatumGetFloat4 DatumGetFloat8
Definition at line 452 of file get_check_data.c.
References Column_info_t::colNumber, Column_info_t::name, and Column_info_t::type.
Referenced by fetch_basic_edge(), fetch_edge(), fetch_edge_with_xy(), fetch_pd_orders(), fetch_point(), fetch_restriction(), fetch_vehicles(), and pgr_fetch_row().
{
     Datum binval;
     bool isnull = false;
     double value = 0.0;
     binval = SPI_getbinval(*tuple, *tupdesc, info.colNumber, &isnull);
     if (isnull)
         elog(ERROR, "Unexpected Null value in column %s", info.name);
     switch (info.type) {
         case INT2OID:
             value = (double) DatumGetInt16(binval);
             break;
         case INT4OID:
             value = (double) DatumGetInt32(binval);
             break;
         case INT8OID:
             value = (double) DatumGetInt64(binval);
             break;
         case FLOAT4OID:
             value = (double) DatumGetFloat4(binval);
             break;
         case FLOAT8OID:
             value = DatumGetFloat8(binval);
             break;
         default:
             elog(ERROR,
                     "Unexpected Column type of %s. Expected ANY-NUMERICAL",
                     info.name);
     }
 #if 0
     // todo Value of specified column was found.
 #endif
     return value;
 }
pgr_SPI_getText()
char* pgr_SPI_getText (HeapTuple * tuple, TupleDesc * tupdesc, Column_info_t info)
under development
Function returns the string representation of the value of the specified column.
Parameters
tuple input row to be examined.
tupdesc input row description.
info contain column information.
Return the string value of the specified column.
SPI_getvalue(*tuple, *tupdesc, info.colNumber);
Returns
Pointer of string is returned.
References
SPI_getvalue DatumGetCString
Definition at line 509 of file get_check_data.c.
References Column_info_t::colNumber.
{
     return DatumGetCString(SPI_getvalue(*tuple, *tupdesc, info.colNumber));
 }