PGROUTING: /home/nazii/pgrouting/include/c_common/time_msg.h File Reference
time_msg.h File Reference
#include <time.h>
#include <stdio.h>
Functions
void time_msg (char *msg, clock_t start_t, clock_t end_t)
Function Documentation
time_msg()
void time_msg (char * msg, clock_t start_t, clock_t end_t)
Definition at line 32 of file time_msg.c.
Referenced by compute(), compute_trsp(), get_edges_5_columns(), get_edges_9_columns(), get_edges_basic(), get_edges_flow(), pgr_get_bigIntArr(), pgr_get_coordinates(), pgr_get_matrixRows(), pgr_get_pd_orders_general(), pgr_get_restrictions(), pgr_get_vehicles_general(), and process().
{
     double elapsed_t = (double)(end_t - start_t) / CLOCKS_PER_SEC;
     elog(DEBUG2,
             "Elapsed time for %s:\n %lf sec = (%lf - %f) / CLOCKS_PER_SEC ",
             msg,
             elapsed_t,
             (double) end_t,
             (double) start_t);
 }